### ISSUE TITLE
[META] REST API Feature descriptions

### ISSUE THREAD

**Issue by samtuke** [phpList/phplist4-core#177]
(moved to https://github.com/phpList/rest-api/issues/76)

**Comment by samtuke** [comment]
@oliverklee Is this format and the level of detail useful?

**Comment by samtuke** [comment]
The 'Required' and 'Optional' labels distinguish between functionality required for initial usefulness vs functionality which can be added later. I believe that 'Optional' functionality is not required for the completion of #125

**Comment by oliverklee** [comment]
> Is this format and the level of detail useful?

Mostly, yes, thanks! Could you please add whether these tasks should work using a web UI, the REST API or the command line?

**Comment by samtuke** [comment]
@oliverklee I have renamed the document to clarify that all listed features relate to the REST API only. This is simpler than labeling each item with multiple interfaces, especially as none of this functionality needs to be exposed via the CLI until after the Web UI reaches maturity.
