### ISSUE TITLE
How to remove phplist community news feed from my phplist software

### ISSUE THREAD

**Issue by ttmubarak** [phpList/phplist4-core#18]
Hello, 

Tell me , how to remove phplist community newsfeed from my phplist software. Which changes I should make?

**Comment by oliverklee** [comment]
@ttmubarak Are you using phpList 3 or 4?

**Comment by oliverklee** [comment]
Closing as there has been no feedback. @ttmubarak If this is still an issue and this is with phpList 4, please feel free to reopen this ticket.
