### ISSUE TITLE
Introduce CS tools

### ISSUE THREAD

**Issue by Soullivaneuh** [phpList/phplist4-core#262]
In order to keep code clean and consistent, I would suggest you to use some CS lint and fix tools.

For PHP: [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) and [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

For JavaScript: [ESLint](https://eslint.org/)

You may also use a SaaS service to help you with code auto-fixing and PR comments.

I made a service like this: https://flintci.io

If you are interested, I can made some Pull Requests. What are you current standard constraints?

Regards.

**Comment by samtuke** [comment]
@Soullivaneuh Thanks for the suggestion. Currently phpList 4 uses the following (visible in .travis.yml):

- phpcs
- phpmd
- phpstan
- php cli for linting
- composer self validation

An automated fixing tool was previously used with phpList 3 but introduced a lot of issues by making a large number of changes to the codebase which were not compatible with all supported of PHP.

There is not yet any JS in phpList 4 but adding ESLint pre-emptively may still be a good idea.

Thoughts @oliverklee ?

**Comment by oliverklee** [comment]
I think we're fine with the current CI setup using Travis. I don't think we'd get much benefit from adding a web service for this.

I'd like to add JavaScript linting once we have some JavaScript (most probably in the web-frontend package).

So @Soullivaneuh, thanks for the proposal and the offer anyway!

**Comment by Soullivaneuh** [comment]
> I don't think we'd get much benefit from adding a web service for this.

The benefits I see:

- Having PR comments to make contribution fix easier to the contributor.
- Having code auto-fixing (optional).
- Reducing Travis jobs duration.

> An automated fixing tool was previously used with phpList 3 but introduced a lot of issues by making a large number of changes to the codebase which were not compatible with all supported of PHP

@samtuke What was the tool? About mine, it is just running the service with the configuration you setup, so you should not have any issue.

I won't insist anymore. Don't hesitate to contact me if you change your mind.

Regards.
