### ISSUE TITLE
Replace the Travis Slack integration with Mattermost

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist4-core#64]

**Comment by oliverklee** [comment]
Done in 6e6eb90. We should remove the old Slack line (no pun intended) altogether, though.

@michield To which Mattermost channel will the notifications get posted?

**Comment by michield** [comment]
I put this in https://github.com/phpList/phplist4-core/blob/master/.travis.yml#L15

which links to Travis builds, but I'm not sure it's working. Also, it's a bit weird to put a secret in a public repo. We may need to keep an eye on it.

**Comment by oliverklee** [comment]
For secrets, Travis provides encrypted environment variables: https://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci

We use this feature on the Emogrifier project: https://github.com/jjriv/emogrifier/blob/master/.travis.yml

**Comment by michield** [comment]
Great! I'll get that sorted out.

**Comment by oliverklee** [comment]
In the phplist4-core repository settings on GitHub, I don't see anything related in "Webhooks" or "Integrations & Services". Shouldn't we have something here for Mattermost (in addition to the API key in .travis.yml)?

**Comment by michield** [comment]
I think there's a bug in Mattermost. My Webhooks keep disappearing. Maybe it's better to re-instate the Slack ones for now.

**Comment by michield** [comment]
I have re-instated slack monitoring on most repos. I will keep an eye on Mattermost developments and will occasionally see if it can be made to work in newer versions. We can keep this ticket open until then.

**Comment by samtuke** [comment]
So the mattermost hoocks are still being silently removed?

**Comment by michield** [comment]
The bug is that they are not shown, and therefore not editable. I think they may still be there, but I can't be sure. However, even if they are there, the payload sent to them is not picked up. Looks like Mattermost can't handle the format sent by Travis.

https://forum.mattermost.org/t/travis-ci-integration/391

**Comment by oliverklee** [comment]
Then closing this for now.
